"""update models

Revision ID: ec7f15b14c57
Revises: c02c22e3d034
Create Date: 2024-01-12 20:56:38.088602

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'ec7f15b14c57'
down_revision = 'c02c22e3d034'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('electricity_readings', 'consumed_kwh')
    op.drop_column('residents', 'monthly_readings')
    op.drop_column('residents', 'readings')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('residents', sa.Column('readings', sa.INTEGER(), autoincrement=False, nullable=True))
    op.add_column('residents', sa.Column('monthly_readings', sa.DATE(), autoincrement=False, nullable=True))
    op.add_column('electricity_readings', sa.Column('consumed_kwh', sa.DOUBLE_PRECISION(precision=53), autoincrement=False, nullable=True))
    # ### end Alembic commands ###
