"""add fliet to eletricity

Revision ID: b1ff3e550656
Revises: 3afdb33c8984
Create Date: 2024-01-22 15:49:11.471945

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'b1ff3e550656'
down_revision = '3afdb33c8984'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('electricity_readings', sa.Column('current_kwh', sa.Integer(), nullable=False))
    op.add_column('electricity_readings', sa.Column('increased_kwh', sa.Integer(), nullable=True))
    op.add_column('electricity_readings', sa.Column('increased_amount', sa.Float(), nullable=True))
    op.add_column('electricity_readings', sa.Column('not_increased_amount', sa.Float(), nullable=True))
    op.drop_column('electricity_readings', 'current_reading')
    op.alter_column('residents', 'home_number',
               existing_type=sa.VARCHAR(),
               nullable=False)
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('residents', 'home_number',
               existing_type=sa.VARCHAR(),
               nullable=True)
    op.add_column('electricity_readings', sa.Column('current_reading', sa.INTEGER(), autoincrement=False, nullable=False))
    op.drop_column('electricity_readings', 'not_increased_amount')
    op.drop_column('electricity_readings', 'increased_amount')
    op.drop_column('electricity_readings', 'increased_kwh')
    op.drop_column('electricity_readings', 'current_kwh')
    # ### end Alembic commands ###
