"""add fliet to eletricity

Revision ID: fe06fe9b59f9
Revises: b1ff3e550656
Create Date: 2024-01-23 14:44:36.040473

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'fe06fe9b59f9'
down_revision = 'b1ff3e550656'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('electricity_readings', sa.Column('consumed_kwh', sa.Integer(), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('electricity_readings', 'consumed_kwh')
    # ### end Alembic commands ###
