"""Initial migration

Revision ID: c02c22e3d034
Revises: 
Create Date: 2024-01-12 16:05:28.053426

"""
from alembic import op
import sqlalchemy as sa

# revision identifiers, used by Alembic.
revision = 'c02c22e3d034'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('residents',
                    sa.Column('id', sa.Integer(), nullable=False),
                    sa.Column('home_number', sa.String(), nullable=True),
                    sa.Column('name', sa.String(), nullable=True),
                    sa.Column('phone_number', sa.String(), nullable=True),
                    sa.Column('monthly_readings', sa.Date(), nullable=True),
                    sa.Column('readings', sa.Integer(), nullable=True),
                    sa.Column('is_deleted', sa.Boolean(), server_default=sa.text('false'), nullable=True),
                    sa.PrimaryKeyConstraint('id')
                    )
    op.create_table('electricity_readings',
                    sa.Column('id', sa.Integer(), nullable=False),
                    sa.Column('resident_id', sa.Integer(), nullable=False),
                    sa.Column('last_reading', sa.Integer(), nullable=True),
                    sa.Column('current_reading', sa.Integer(), nullable=False),
                    sa.Column('payment_status', sa.Boolean(), nullable=True),
                    sa.Column('amount', sa.Float(), nullable=True),
                    sa.Column('consumed_kwh', sa.Float(), nullable=True),
                    sa.Column('created_date', sa.Date(), nullable=True),
                    sa.Column('is_deleted', sa.Boolean(), server_default=sa.text('false'), nullable=True),
                    sa.ForeignKeyConstraint(['resident_id'], ['residents.id'], ondelete='RESTRICT'),
                    sa.PrimaryKeyConstraint('id')
                    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('electricity_readings')
    op.drop_table('residents')
    # ### end Alembic commands ###
